#!/bin/bash

MYNAME=$(basename "${0}")
USER="${USER}"
SERVER="$(hostname --fqdn)"
PROJECT=""
HTTPPORT="8443"
SSHPORT="29418"

function usage {
  echo "Usage: ${MYNAME} [-u <username>] [-p <project>] [-s <server>] [-x <httpport>] [-y <sshport>] -- <reponame>"
  exit 1
}

if [ $# -eq 0 ]; then
  usage
fi


while getopts ":hu:p:s:x:y:" opt; do
  case ${opt} in
    h)
      usage
      ;;
    u)
      USER=${OPTARG}
      ;;
    p)
      PROJECT="/${OPTARG}"
      ;;
    s)
      SERVER=${OPTARG}
      ;;
    x)
      HTTPPORT=${OPTARG}
      ;;
    y)
      SSHPORT=${OPTARG}
      ;;
    \?)
      echo "Invalid option: -${OPTARG}" >&2
      usage
      ;;
  esac
done

shift $((OPTIND-1))
REPO=$1

if [ -z "${REPO}" ]; then
  echo "No repository name provided" >&2
  usage
fi
HTTPURL="https://${USER}@${SERVER}:${HTTPPORT}/r${PROJECT}/${REPO}.git"
SSHURL="ssh://${USER}@${SERVER}:${SSHPORT}${PROJECT}/${REPO}.git"

s=$(printf "%-${#REPO}s" "=")

mkdir ${REPO}
cd ${REPO}
git init
git remote add -m master origin "${HTTPURL}"

cat << EOF > README.md
${REPO}
${s// /=}
EOF

git add .
git commit -m 'Initial commit'
git push origin master
git remote set-url origin "${SSHURL}"
git branch -u origin/master master
