#!/bin/bash

MYNAME=$(basename "${0}")
USER="${USER}"
SERVER="$(hostname --fqdn)"
PROJECT=""
HTTPPORT="8443"
SSHPORT="29418"

function usage {
  echo "Usage: ${MYNAME} [-u <username>] [-p <project>] [-s <server>] [-x <httpport>] [-y <sshport>] -- <reponame>"
  exit 1
}

if [ $# -eq 0 ]; then
  usage
fi


while getopts ":hu:p:s:x:y:" opt; do
  case ${opt} in
    h)
      usage
      ;;
    u)
      USER=${OPTARG}
      ;;
    p)
      PROJECT="/${OPTARG}"
      ;;
    s)
      SERVER=${OPTARG}
      ;;
    x)
      HTTPPORT=${OPTARG}
      ;;
    y)
      SSHPORT=${OPTARG}
      ;;
    \?)
      echo "Invalid option: -${OPTARG}" >&2
      usage
      ;;
  esac
done

shift $((OPTIND-1))
REPO=$1

if [ -z "${REPO}" ]; then
  echo "No repository name provided" >&2
  usage
fi

SSHURL="ssh://${USER}@${SERVER}:${SSHPORT}${PROJECT}/${REPO}.git"
GITHUBURL="git@github.com:${USER}/${REPO}.git"

# pull in the gitblit repository
git clone ${SSHURL}
if [ $? -ne 0 ]; then
  echo "Failed to clone repository from ${SSHURL}"
  exit 1
fi
cd ${REPO}
git remote rename origin gitblit

# create the github repository
curl -u "${USER}" https://api.github.com/user/repos -d '{"name":"'${REPO}'"}' >/dev/null
if [ $? -ne 0 ]; then
  echo "Failed to create github repository from ${REPO}"
  exit 1
fi

# add the github remote and push everything upstream
git remote add -m master github ${GITHUBURL}
git push github master

# "git pull" shall pull the master branch from github
git branch -u github/master master
